# permissions for end users to edit civoclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: civocluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: clusterify
    app.kubernetes.io/part-of: clusterify
    app.kubernetes.io/managed-by: kustomize
  name: civocluster-editor-role
rules:
- apiGroups:
  - clusters.core.clusterify.io
  resources:
  - civoclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.core.clusterify.io
  resources:
  - civoclusters/status
  verbs:
  - get
